import diagnostics_linear_inference_regression_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace diagnostics_linear_inference_regression_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end diagnostics_linear_inference_regression_theorem_canonical_lane_mathlib
end HautevilleHouse
